from lexer.Token import Token, TokenType


SEMICOLON_TOKEN = Token(TokenType.SEMICOLON)
POINT_TOKEN = Token(TokenType.POINT)
COMMA_TOKEN = Token(TokenType.COMMA)
OPEN_PARENTHESIS_TOKEN = Token(TokenType.PARENTHESIS_OPENING)
CLOSE_PARENTHESIS_TOKEN = Token(TokenType.PARENTHESIS_CLOSING)
BOOLEAN_TOKEN = Token(TokenType.BOOLEAN)
NUMBER_TOKEN = Token(TokenType.NUMBER)
STRING_TOKEN = Token(TokenType.STRING)
EOF_TOKEN = Token(TokenType.EOF)
